[features]
seeds = false

[programs.localnet]
nft_vote = "yJ28bokcTwpT1orZ8yUGPrwYboV46KDDPituAGD7PGe"

[programs.devnet]
nft_vote = "yJ28bokcTwpT1orZ8yUGPrwYboV46KDDPituAGD7PGe"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/yihauchen/.config/solana/id.json"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[[test.validator.clone]]
address = "PwDiXFxQsGra4sFFTT8r1QWRMd4vfumiWC1jfWNfdYT"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
